### PR TITLE
feat(minishift): Set hyperkit as default vm on macOs

### LINKED ISSUE #31: install script fails with `xhyve` driver on macOS
When running the `etc/install-on-minishift.sh` script on macOS, I get the following error:
````
./etc/scripts/install-on-minishift.sh
+ OPENSHIFT_VERSION=v3.11.0
+ MEMORY=10GB
+ CPUS=4
+ DISK_SIZE=50g
+ minishift profile delete knative --force
Profile 'knative' deleted successfully.
Switching to default profile 'minishift' as the active profile.
+ minishift profile set knative
Profile 'knative' set as active profile.
+ minishift config set openshift-version v3.11.0
+ minishift config set memory 10GB
No Minishift instance exists. New 'memory' setting will be applied on next 'minishift start'
+ minishift config set cpus 4
No Minishift instance exists. New 'cpus' setting will be applied on next 'minishift start'
+ minishift config set disk-size 50g
No Minishift instance exists. New 'disk-size' setting will be applied on next 'minishift start'
+ minishift config set image-caching true
+ minishift addons enable admin-user
Add-on 'admin-user' enabled
+ minishift start
-- Starting profile 'knative'
-- Check if deprecated options are used ... OK
-- Checking if https://github.com is reachable ... OK
-- Checking if requested OpenShift version 'v3.11.0' is valid ... OK
-- Checking if requested OpenShift version 'v3.11.0' is supported ... OK
-- Checking if requested hypervisor 'xhyve' is supported on this platform ... OK
-- Checking if xhyve driver is installed ... FAIL
   See the 'Setting Up the Virtualization Environment' topic (https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html) for more information
````
I wonder if the script should rather use `hyperkit` as it seems the be the preferred VM driver upstream: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver.

Having `hyperkit` already installed on my machine, I just needed to add the following line:
````
minishift config set vm-driver hyperkit
````

### PR DESCRIPTION
**Pull request by rhuss**
Fixes #31.

### CODE REVIEW

**Comment by xcoulon** [comment]
thanks for taking care of this, @rhuss 🙌

**Comment by bbrowning** [comment]
@VeerMuchandi does this solve the same specific issue you were solving with #30? Or do we need both - VM drivers that are more easily configured AND changing the default on Mac?

**Comment by rhuss** [comment]
@bbrowning @VeerMuchandi I adapted this PR now to respect a vm-driver set in the default profile (minishift), too.

The vm-driver to choose will be detected by (in this order):

* from the env var VM_DRIVER
* from the minishift vm-driver config in the *minishift* / default profile
* "hyperkit" on macOs

If none is found, then minishift is started without vm-driver option (which falls back to minishift internal defaults)

The question is, whether the vm-driver values should be picked up from an existing "knative" profile, the current profile, or the default profile. I opt for the default profile as this is the default the user has set for its installation.

**Comment by jcrossley3** [comment]
Thank you!

**Pull request merged**
