### PR TITLE
use set -ex in install-on-minishift.sh

### PR DESCRIPTION
**Pull request by vorburger**

### CODE REVIEW

**Comment by vorburger** [comment]
@jcrossley3

**Comment by jcrossley3** [comment]
I'm not sure I want this. Should I? :)

**Comment by bbrowning** [comment]
`set -e` isn't a bad idea generally - it causes the script to exit if any of commands runs return a non-zero exit status. I feel like I tried this once before in installation_functions.sh and things broke - we'll need to ensure the script is setup so that we can use `set -e` and nothing unexpectedly cause the script to exit.

**Comment by vorburger** [comment]
I like to do this almost always, because I find it makes the output of any script easier to understand for a human in case anything fails half way through, because it "fails early", instead of carrying on, and failing with subsequent errors due to earlier failures.

It was just a small general suggestion though, feel free to close it if you don't want this here for some reason. I've used it in https://github.com/knative/docs/pull/976/ where I took the liberty to take "inspiration" (cough) from this script.

**Comment by vorburger** [comment]
>  we'll need to ensure the script is setup so that we can use set -e and nothing unexpectedly cause the script to exit.

Note cf58d64429fe3e600b50d2edf63689ff1e8b572a re ^^^ this.

BTW: Just noticed @bbrowning #26 and how you did `if [ $? -eq 0 ]` in https://github.com/openshift-cloud-functions/knative-operators/commit/0c8bbb49cb127fafb625c5c1b44deed31f7191f8 .. using set -e is an alternative which is perhaps nicer? Just a thought.

> I've used it in knative/docs#976

strike that, I think I'll abandon https://github.com/knative/docs/pull/976 in favour of https://github.com/knative/docs/pull/982, if OK for you. (Ergo I think this would be "nice to have" here.)

**Pull request merged**
