### PR TITLE
Bump to Maistra 0.6.0

### PR DESCRIPTION
**Pull request by bbrowning**

### CODE REVIEW

**Comment by bbrowning** [comment]
As an update, I've yet to get anything newer than Maistra 0.6 working on OpenShift 4. So, let's hold off on this a bit longer until I can track down what's happening.

**Comment by bbrowning** [comment]
I haven't manually tested this change yet, but CI confirms that Maistra 0.6 and OpenShift 4 are happy together.

**Comment by bbrowning** [comment]
I've manually tested this w/ install_on_minishift.sh and everything looked fine.

/cc @jcrossley3

**Comment by jcrossley3** [comment]
You feel good about merging it, @bbrowning ?

**Pull request merged**
